# Generated by Django 5.1.5 on 2025-01-28 15:21

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_homepage_body"),
    ]

    operations = [
        migrations.RenameField(
            model_name="homepage",
            old_name="body",
            new_name="actu",
        ),
        migrations.AddField(
            model_name="homepage",
            name="alaune",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="entete",
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
