# Generated by Django 5.1.5 on 2025-01-28 15:39

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_rename_body_homepage_actu_homepage_alaune_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="accueil",
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
