# Generated by Django 5.1.5 on 2025-01-28 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_homepage_accueil"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="accueil",
        ),
    ]
