# Generated by Django 5.1.5 on 2025-01-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="titre",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
