# Generated by Django 5.1.5 on 2025-01-28 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0002_article_titre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="titre",
        ),
    ]
