# Generated by Django 5.1.5 on 2025-02-07 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0004_alter_categorie_options_articlecategorie"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="indexboutique",
            name="description",
        ),
    ]
